name: Download and push model

on:
  push:
  
jobs:
  model:
    name: Download and push model
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Download model
        run: |
          MODEL_NAME=model
          #curl -L http://download.tensorflow.org/models/object_detection/ssdlite_mobilenet_v2_coco_2018_05_09.tar.gz -o $MODEL_NAME.tar.gz
          curl -L http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz -o $MODEL_NAME.tar.gz
          echo "$MODEL_NAME downloaded, extracting:"
          mkdir $MODEL_NAME
          tar -xzvf $MODEL_NAME.tar.gz -C $MODEL_NAME --strip-components 1
          mkdir -p app/model
          mv $MODEL_NAME/saved_model/saved_model.pb app/model
          rm -r $MODEL_NAME*
          echo "Model replaced."
      - name: Push model
        run: |
          git config --global user.name "lfbatista"
          git config --global user.email "batistaluisfilipe@gmail.com"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Update saved_model.pb"
          git push

